version: '3.5' 
services: 
  igparser: 
    privileged: false
    user: 1000:1000
    build: .
    restart: always
    volumes:
      - "./logs:/logs"
    environment:
      IG_PARSER_PORT: "8080"
      IG_PARSER_LOGGING: "true"
      IG_PARSER_LOGGING_PATH: "/logs"
    ports: 
      - '4040:8080'
    networks:
      - tunnel_network
networks:
  tunnel_network:
    external: true
